# Generated by Django 2.2 on 2021-04-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iToys', '0002_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
