# Generated by Django 2.2 on 2021-04-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iToys', '0003_auto_20210427_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='header_image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to=''),
        ),
    ]
